backend:
  name: github
  repo: drhomepage/drhomepage.github.io
  base_url: https://oauth.digitalrapids.work
  branch: main

media_folder: 'admin/assets/images'
public_folder: 'assets/images'

collections:
  - name: 'page'
    label: 'Page Content'
    files:
      - name: 'page'
        label: 'Page Config'
        file: '_data/page.yml'
        fields:
          - name: 'translations'
            label: 'Translations'
            widget: 'list'
            fields:
              - label: 'Key'
                name: 'key'
                widget: 'string'
              - label: 'English'
                name: 'en'
                widget: 'string'
              - label: 'German'
                name: 'de'
                widget: 'string'
